((nil . ((tab-width . 8)
	 (indent-tabs-mode . t)))
 (c++-mode . ((c-basic-offset . 8)
	      (tab-width . 8)
	      (indent-tabs-mode . t)
	      (compile-command . "make -C ../build -j 3 install")))
 ((c-mode . ((c-basic-offset . 8)
	     (tab-width . 8)
	     (indent-tabs-mode . t)
	     (compile-command . "make -C ../build -j 3 install")))))
